os: windows
language: node_js
node_js:
- '9.9.0'
script: node -v
before_deploy:
  - mkdir build
  - cd build
  - mkdir output
  - cd ../app
  - npm install electron -g
  - npm install electron-packager -g
  - npm install electron-builder -g
  - npm install
  - npm install --global --production windows-build-tools@4.0.0
  - npm install --save-dev electron-rebuild
  - .\\node_modules\\.bin\\electron-rebuild.cmd
  - electron-builder --win --ia32
  - mv ../build/TheDesk-setup.exe ../build/output/TheDesk-setup-ia32.exe
  - mv ../build/TheDesk*.exe ../build/output/TheDesk-ia32.exe
  - electron-builder --win --x64
  - mv ../build/TheDesk-setup.exe ../build/output/TheDesk-setup.exe
  - mv ../build/TheDesk*.exe ../build/output/TheDesk.exe
  - electron-packager ./ TheDesk --executable-name="TheDesk" --app-copyright="Copyright (c) TheDesk 2018 Cutls.com 2015 All Right Reserved" --platform=linux --arch=x64,ia32 --electron-version=3.0.10 --overwrite
  - 7z a TheDesk-linux-x64.zip TheDesk-linux-x64
  - 7z a TheDesk-linux-ia32.zip TheDesk-linux-ia32
  - cd ../
deploy:
  provider: releases
  api_key:
    secure: jndR02p5KRTtcJk18b3YsXL2cC+yzEf1AOqXdpWciF8f3lO5oY01jlxd17xdHIcK7VywSsLVZpLToSdqAoIEhJ5OxEQ/FmA3FlmbwwD6ou13gLa4VGIvsBHveCmKGjVu0Z++atIy76tZYU1SOWFWv4B0ZhnVz2ca2VZynvLgw3YNsPJH7rHO966GXgRkGYJAJ4UvLg3sj/iztVh2FSfbUj5IGO1e/JHJO63wAo1MSQtRjkutVgl/djnBLC6vbL4YHkM3Ynpkx/YQEcxwrmeY0Ra8D5yYDq4MNIDMmZahWC+k4u2eA2Cj2ifBFNxbZvTN75vLwRBp6DsTNHsiqkXrSPDBdNeet31RbwTQ6LtsK8jqmL4S/59dmLcj7uCU2WxyBLPbJdbdZWlqW2ZQvfQY8QVAYy7S3MiHQWQN0oP5wqXk89jcgR42ig/zsqFNPpXHM4mExR7l/gDLPg0j9c3XEF6sWtk3FmJN1i4+B+9kn09b6UKlV7EFPKp8XcFNrz4ZcE9/I8lKwsqLVG2jAXIk7Z9LwDRcAmK5eG348X5zwFtOY6raKIvRw2cn92bPnEI+55v8A4WANS2647GFTgxHj30D0d/sOZmJ5BS34zpdWTgE0AlKg7sOqkncjqoW5J5zCh5Ow7b3KXvEvlAts44mAag8tZTectxMP4iguXvTnv4=
  file: 
    - "C:\Users\travis\build\cutls\TheDesk\build\TheDesk.exe"
    - "C:\Users\travis\build\cutls\TheDesk\build\TheDesk-setup.exe"
    - "C:\Users\travis\build\cutls\TheDesk\build\TheDesk-ia32.exe"
    - "C:\Users\travis\build\cutls\TheDesk\build\TheDesk-setup-ia32.exe"
    - "C:\Users\travis\build\cutls\TheDesk\app\TheDesk-linux-x64.zip"
    - "C:\Users\travis\build\cutls\TheDesk\app\TheDesk-linux-ia32.zip"
  on:
    repo: cutls/TheDesk
skip_cleanup: true