files:
  - source: /app/view/make/language/en/*.json
    translation: /app/view/make/language/%language%/*.json
  - source: /app/js/lang/lang.en.json
    translation: /app/js/lang/lang.%language%.json
